# Generated by Django 3.2.9 on 2021-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211117_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='not_processed_income',
            field=models.IntegerField(default=0),
        ),
    ]
