# Generated by Django 3.2.9 on 2022-02-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220216_0725'),
        ('account', '0003_order_paid'),
    ]

    operations = [
    ]
