# Generated by Django 3.2.6 on 2022-02-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='wallet',
        ),
    ]
