# Generated by Django 3.2.6 on 2022-02-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_0002_auto_20220216_0725_0003_order_paid'),
        ('account', '0004_remove_doctor_wallet'),
    ]

    operations = [
    ]
