# Generated by Django 3.2.9 on 2021-11-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211115_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('specialty', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Doctor'), (2, 'Patient')], default=2, verbose_name='user type'),
        ),
    ]
